task:
  name: linux_build
  container:
    image: gcc:latest
  install_script:
    - apt-get install cmake
  script:
    - git submodule update --init --recursive
  test_script:
    - cd tests
    - ./test_driver.sh

